apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstoreapi
  labels:
    app: book-store-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: bookstoreapi
  template:
    metadata:
      labels:
        app: book-store-api
        service: bookstoreapi
    spec:
      containers:
        - name: bookstoreapi
          image: congdang/bookstoreapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: bookstoreapi
  labels:
    app: book-store-api
    service: bookstoreapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: bookstoreapi